[phases.setup]
nixPkgs = ["chromium", "chromedriver", "tesseract", "which"]

[phases.build]
cmds = ["which chromium || echo 'chromium not found'", "which chromedriver || echo 'chromedriver not found'"]