# Generated by Django 3.2.8 on 2025-11-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_path',
            field=models.CharField(default='/', max_length=200, verbose_name='網址'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=200, verbose_name='網址'),
        ),
    ]
