# Generated by Django 3.2.8 on 2025-11-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20251105_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url_path',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
